project_name: wikindexer

builds:
  - binary: wikindexer-collector
    main: ./cmd/collector
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

brews:
  - repository:
      owner: pthomison
      name: homebrew-tools

    service: |
      run opt_bin/"wikindexer"
      log_path var/"log/wikindexer-stdout.log"
      error_log_path var/"log/wikindexer-stderr.log"
      working_dir var/"lib/wikindexer"

    post_install: |
      (var/"lib/wikindexer").mkpath

before:
  hooks:
    - go mod tidy
    - go fmt ./...

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"
